config/routes.rb
Rails.application.routes.draw do
  root 'home#index'  
  resources :blocks
  resources :friends
  resources :messages
  resources :sessions, only: [:new, :create]
  resources :users
  get 'log_out' => 'sessions#destroy'
  get 'sent_index' => 'messages#sent_index'
  get 'unfriend' => 'friends#destroy'
  get 'unblock' => 'blocks#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
	belongs_to :user, class_name: 'User'
	belongs_to :blocked_user, class_name: 'User'
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user, class_name: 'User'
	belongs_to :friend, class_name: 'User'

end

app/models/message.rb
class Message < ApplicationRecord
	belongs_to :sender, class_name: 'User'
	belongs_to :recipient, class_name: 'User'

	
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	validates :email, presence: true, uniqueness: true
	has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'
	has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
	has_many :friends, class_name: 'Friend', foreign_key: 'friend_id'
	has_many :users, class_name: 'Friend', foreign_key: 'user_id'
	has_many :users_block, class_name: 'Block', foreign_key: 'user_id'
	has_many :blocked_users_block, class_name: 'Block', foreign_key: 'blocked_user_id'
	def to_s
		name
	end

	def received_messages
		Message.where(recipient_id: id).order('created_at desc')
	end

	def friends
		Friend.where(user_id: id)
	end

	def blocked_users_block
		Block.where(user_id: id)
	end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  

  def current_user
 	return @current_user if @current_user
 	if session[:user_id]
  	 @current_user ||= User.find(session[:user_id])
  	end
  end
end

app/controllers/blocks_controller.rb
class BlocksController < ApplicationController
	def index
		@blocked_users = current_user.blocked_users_block	
	end

	def new
		if params[:user].present?
		@blocked_user = User.find(params[:user])
		end
		@user = current_user
		if params[:confirm]=="yes"
			@add_new_blocked_user = Block.new(user_id: @user.id, blocked_user_id: @blocked_user.id)
			if @add_new_blocked_user.save
				flash[:success] = "#{@blocked_user.name} is blocked now"
				redirect_to users_path
			end
		end
		if params[:confirm]=="no"
			redirect_to users_path
		end
	end

	def destroy
		@blocked_user = Block.find(params[:id]).destroy
		redirect_to :back
	end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
	def index
		@friends = current_user.friends		
	end

	def new
		if params[:user].present?
		@friend = User.find(params[:user])
		end
		@user = current_user
		if params[:confirm]=="yes"
			@add_new_friend = Friend.new(user_id: @user.id, friend_id: @friend.id)
			if @add_new_friend.save
				flash[:success] = "#{@friend.name} is in your friend list now"
				redirect_to users_path
			end
		end
		if params[:confirm]=="no"
			redirect_to users_path
		end
	end

	def destroy
		@friend = Friend.find(params[:id]).destroy
		redirect_to :back
	end
	
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if current_user
  		redirect_to messages_path
  	end
  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	

	def index
		#Message.new(:subject => 'Test_message_7', :body => 'helloooooooooooooooo', :sender_id => 1, :recipient_id => 2).save
		@messages = current_user.received_messages
		@blocked_users = current_user.blocked_users_block
		@blocked_users.each do |block|
			@banned_message = Message.where(:sender_id => block.blocked_user.id)
			@messages = @messages -@banned_message
		end

		
	end

	def sent_index
		@messages = current_user.sent_messages
	end

	def show
		@message = Message.find(params[:id])
		if @message.read_times != nil
			@message.read_times += 1
			@message.save
		else
			@message.read_times = 1
			@message.read_at = Time.now.to_datetime
			@message.save
		end

	end

	def new
		@friends = current_user.friends

			@friends.each do |friend|
				if @a
				@a += User.where(:id => friend.friend.id)
				else
				@a = User.where(:id => friend.friend.id)
				end 
			end # @a la danh sach tat ca ban be
		if @a==nil
			@a = current_user.friends
		end
		if params[:recipient_id].present?
			@recipient =  User.find(params[:recipient_id])
			@message = Message.new(subject: params[:subject], body: params[:body], recipient_id: @recipient.id)
			(session[:recipients_id] ||= []) << params[:recipient_id]
			@c = session[:recipients_id].uniq
			@recipient = []
			@name = []
			@c.each do |f|
				@q = User.find(f)
				@recipient << @q	
				@name << @q.name
			end
			@a = @a - @recipient



		else
			session.delete(:recipients_id)
			@message = Message.new(subject: params[:subject], body: params[:body])	
		end
	end

	def create
		@recipients_id = session[:recipients_id]

		@recipients_id.each do |id|	
			@message = Message.new message_params
			@message[:sender_id] = current_user.id
			@message[:recipient_id] = User.find(id).id
			@message.save
		end
			if @message.save
				flash[:success] = "Your message has been sent"
				redirect_to root_path
			else
				flash[:error] = "Please select at least one recipient"
				redirect_to :back
			end
	end

	private
	def message_params
		params.require(:message).permit(:subject, :body, :recipient_id)	
	end

end
	

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	@user = User.find_by(email: params[:email])
  	if @user
  		if @user.authenticate(params[:password])
  			flash[:success] = "Sign In Successfully."
  			session[:user_id] = @user.id
  			
  			redirect_to root_path 
  		else
  			flash.now[:error] =" Wrong password."
  			render 'new'
  		end
  	else
  		flash[:error] =" User not found."
  		render 'new'
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to root_path, flash: {alert: "Logged out!!!"} 	
  end
end



#<% if @recipient %>
 #         <td><%= @recipient.name %></td>
  #        <% else %>
   #       Select
    #      <% end %>

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users=User.where.not(:id => current_user.id)
		@friend=current_user.friends
		@friend.each do |friend|
			@b= User.where(:id => friend.friend.id) 
			@users = @users - @b
		end
		@blocked_users = current_user.blocked_users_block
		@blocked_users.each do |block|
			@b= User.where(:id => block.blocked_user.id) 
			@users = @users - @b
		end
	end

	def new
		@user = User.new(email: params[:email], name: params[:name])
	end

	def create
		@user = User.new user_params
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome #{@user.name}, Let's rock and roll"
			redirect_to root_path
		else
			render 'new'
		end
		
	end

	def edit
		@user=User.find(current_user.id)
		#@user.avatar_url = params[:avatar_url]
		#@user.save
	end


	private

	def user_params
		params.require(:user).permit(:name, :email, :password)	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blocks_helper.rb
module BlocksHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def bootstrap_class_for flash_type
		{ success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
	end

	def flash_messages(opts = {})
		flash.map do |msg_type, message|
			content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
				content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
			end
		end.join.html_safe
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blocks/index.html.erb
<center>
<h1> Black List </h1>
</center>

<% if @blocked_users.empty? %>
	<div class="alert alert-danger"> You have no user in black list. </div>
<% end %>
<div class="row">
	<div class="col col-md-9">
		<table class="table table-triped">
			<thead class="thead bg-success">
				<tr>
					<th> Name </th>
					<th> Email </th>
					<th> Added at </th>
					<th> Option </th>
				</tr>
			</thead>
			<tbody>
			<% @blocked_users.each do |f| %>
				<tr class="table-danger">
				<td><%= f.blocked_user.name %></td>
				<td><%= f.blocked_user.email %></td>
				<td><%= f.blocked_user.created_at %></td>
				<td><%= link_to "Unblock", unblock_path(:id => f.id), data: { confirm: "Are you certain you want to unfriend #{f.blocked_user.name} ?"  } %> </td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/blocks/new.html.erb
<center>
<h1> Block User </h1>
</center>

<p>Do you want to block user <b><%= @blocked_user.name %></b> ? </p>
<%= link_to "Yes", new_block_path(:user => @blocked_user ,:confirm => 'yes') ,class: 'btn btn-primary' %>
<%= link_to "No", new_block_path(:user => @blocked_user ,:confirm => 'no') ,class: 'btn btn-warning' %>

app/views/friends/index.html.erb
<center>
<h1> Friend List </h1>
</center>

<% if @friends.empty? %>
	<div class="alert alert-danger"> You have no friend. </div>
<% end %>
<div class="row">
	<div class="col col-md-9">
		<table class="table table-triped">
			<thead class="thead bg-success">
				<tr>
					<th> Name </th>
					<th> Email </th>
					<th> Added at </th>
					<th> Option </th>
				</tr>
			</thead>
			<tbody>
			<% @friends.each do |friend| %>
				<tr class='table-success'>
				<td><%= friend.friend.name %></td>
				<td><%= friend.friend.email %></td>
				<td><%= friend.friend.created_at %></td>
				<td><%= link_to "Unfriend", unfriend_path(:id => friend.id), data: { confirm: "Are you certain you want to unfriend #{friend.friend.name} ?"  } %> </td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/friends/new.html.erb
<center>
<h1> Add friend </h1>
</center>

<p>Do you want to add <b><%= @friend.name %></b> as your friend </p>
<%= link_to "Yes", new_friend_path(:user => @friend.id ,:confirm => 'yes') ,class: 'btn btn-primary' %>
<%= link_to "No", new_friend_path(:user => @friend.id ,:confirm => 'no') ,class: 'btn btn-warning' %>

app/views/home/index.html.erb
<center>
<h1>Welcome to Ruby Chat</h1>
</center>

<body>
<center>
	<%= link_to "Sign Up", new_user_path , class: "btn btn-outline-primary" %>

	<%= link_to "Sign In", new_session_path, class: "btn btn-primary" %>
</center>
</body>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="<%= root_path %>">Ruby Chat</a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <li class="nav-item">
          <%= link_to "Log out #{current_user}", log_out_path,  class: "nav-link text-danger" %>
        </li>
        <li class="nav-item">
          <%= link_to "Users", users_path, class: "nav-link text-primary" %>
        </li>
        <li class="nav-item">
            <%= link_to "Friend list", friends_path, class: "nav-link text-success" %>
          </li>
          <li class="nav-item">
            <%= link_to "Black List", blocks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Account Setting", edit_user_path(current_user.id), class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_path , class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign In", new_session_path, class: "nav-link" %>
          </li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rubychat</title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
  	<%= flash_messages %>
  	<%= render 'layouts/navbar'%>
    <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<center>
<h1> Inbox </h1>
</center>

<% if @messages.empty? %>
	<div class="alert alert-danger"> You have no message. </div>
<% end %>
<div class="row">
<div class="col col-md-9">
<table class="table table-triped">
	<thead class="thead thead-default">
		<tr>
			<th> Sender </th>
			<th> Subject </th>
			<th> Received time </th>
			<th> Read time </th>
		</tr>
	</thead>
	<tbody>
		<% @messages.each do |message| %>
			<% if message.read_at == nil %>		
			<tr class="table-info">
				<td><%= link_to message.sender, message_path(:id => message.id) %></td>
				<td><%= message.subject %></td>
				<td><%= message.created_at %></td>
				<td> Unread </td>
			</tr>
			<% else %>
			<tr> 
				<td><%= link_to message.sender, message_path(:id => message.id) %></td>
				<td><%= message.subject %></td>
				<td><%= message.created_at %></td>
				<td><%= message.read_at %></td>
			</tr>
			<% end %>
		<% end %>
	</tbody>
</table>
</div>
<div class="col col-md-3">
	<%= link_to "New message", new_message_path, class: 'btn btn-outline-primary btn-lg', style: 'padding-left: 29px; padding-right: 28px;' %><br>
	<%= link_to "Sent messages", sent_index_path, class: 'btn btn-outline-success btn-lg' %>
</div>
</div>

app/views/messages/new.html.erb
<center>
	<h1> Create New Message </h1>
</center>

<% if @message.errors.size > 0 %>
<div class="alert alert-danger">
<%= @message.errors.full_messages.to_sentence %>
</div>
<% end %>
<div class="card" >
	<div class="card-block" >

		<div class="form-inline">	
			<b style='margin-right: 20px;'> To: </b>
			<% if @name %>
			<b class="text-primary"><%= @name.to_sentence %></b>
			<% end %>
		</div>


		<%= form_for @message do |f| %>

		<div class="dropdown">
				<a class="btn btn-secondary dropdown-toggle" href="https://example.com" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
					Add recipient
				</a>
				<div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
					<% @a.each do |friend| %>
					<%= link_to friend.name, new_message_path(:recipient_id => friend.id), class: "dropdown-item" %>
					<% end %>
				</div>
			</div>

		<div class="form-group">
			<%= f.label :subject  %>
			<%= f.text_field :subject, class: 'form-control'  %>
		</div>
		<div class="form-group">
			<%= f.label :body  %>
			<%= f.text_field :body, class: 'form-control', :size => '100x100'  %>
		</div>

		<div class="form-group">
			<%= f.submit 'Send', class: 'btn btn-primary'  %>
		</div>
		<% end %>

	</div>
</div>

app/views/messages/sent_index.html.erb
<center>
	<h1> Sent Messages </h1>
</center>

<% if @messages.empty? %>
	<div class="alert alert-danger"> You have no message. </div>
<% end %>
<div class="row">
<div class="col col-md-9">
<table class="table table-triped">
	<thead class="thead thead-default">
		<tr>
			<th> Sent to </th>
			<th> Subject </th>
			<th> Sent_time </th>
			<th> Read time </th>
		</tr>
	</thead>
	<tbody>
		<% @messages.each do |message| %>
			<% if message.read_at == nil %>		
			<tr class="table-info">
				<td><%= message.recipient %></td>
				<td><%= message.subject %></td>
				<td><%= message.created_at %></td>
				<td> Unread </td>
			</tr>
			<% else %>
			<tr> 
				<td><%= message.recipient %></td>
				<td><%= message.subject %></td>
				<td><%= message.created_at %></td>
				<td><%= message.read_at %></td>
			</tr>
			<% end %>
		<% end %>
	</tbody>
</table>
</div>
<div class="col col-md-3">
</div>
</div>

app/views/messages/show.html.erb
<center>
<h1> Message from <%= @message.sender.name %> </h1>
</center>
<% if @message.read_times == 1 %>
	<td><%= @message.body %></td>
<% else %>
	<h6>The message has already been read. You only read once </h6>
<% end %>

app/views/users/edit.html.erb
<center>
	<h1> Update User </h1>
</center>

<body>
	
</body>

app/views/users/index.html.erb
<center>
<h1> List of All Users </h1>
</center>

<div class="row">
	<div class="col col-md-10">
		<table class="table table-triped">
			<thead class="thead bg-success ">
				<tr>
					<th> Name </th>
					<th> Email </th>
					<th> Status / Options </th>
				</tr>
			</thead>
			<tbody>
			<% @users.each do |user| %>
				<tr class="table-info" >
					<td><%= user.name %></td>
					<td><%= user.email %></td>
					<td><%= link_to "Add As Friend", new_friend_path(user: user.id)%> |
					<%= link_to "Block user", new_block_path(user: user.id) %> </td>
				</tr>
				<% end %>
			<% @friend.each do |friend| %>	
				<tr class="table-success" >
					<td><%= friend.friend.name %></td>
					<td><%= friend.friend.email %></td>
					<td><%= 'Friend' %></td>
				</tr>
			<% end %>
			<% @blocked_users.each do |block| %>	
				<tr class="table-danger" >
					<td><%= block.blocked_user.name %></td>
					<td><%= block.blocked_user.email %></td>
					<td><%= 'Blocked' %></td>
				</tr>
			<% end %>
			</tbody>
		</table>
	</div>
	<div class="col col-md-2">
	</div>
</div>

app/views/users/new.html.erb
<h1> Sign Up </h1>

<%= form_for @user do |f| %>
<% if @user.errors.size > 0 %>
<div class="alert alert-danger">
<%= @user.errors.full_messages.to_sentence %>
</div>
<% end %>
<div class="form-group">
<%= f.label :name  %>
<%= f.text_field :name, class: 'form-control'  %>
</div>
<div class="form-group">
<%= f.label :email  %>
<%= f.text_field :email, class: 'form-control'  %>
</div>
<div class="form-group">
<%= f.label :password  %>
<%= f.password_field :password, class: 'form-control'  %>
</div>
<div class="form-group">
<%= f.submit 'Sign Up', class: 'btn btn-primary'  %>

</div>
<% end %>